apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datastory-collector.fullname" . }}-config
  labels:
    {{- include "datastory-collector.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Values.datastory_config | toJson | indent 4 }}
